# Generated by Django 4.2 on 2023-04-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=128)),
                ('numbers', models.CharField(max_length=128)),
            ],
        ),
    ]
